---
title: Join the Hackathon!
---


### You're perfect for this hackathon if...

- You like higher-order network analysis or want to learn more about it. 
- You have some experience with programming, especially in a language like Python, R, Julia, or Matlab. 
    - We anticipate that most groups working in this event will work in Python. Python will be the only language that the workshop organizers can guarantee support and troubleshooting for. 
- You want to meet cool new people and collaborate with them in a casual, collaborative environment. 

### Code of Conduct

A Higher-Order Hackathon is dedicated to a harassment-free, welcoming conference experience for everyone. Our code of conduct can be found [here.](https://www.philchodrow.prof/higher-order-hackathon/coc.html) 

### How to Apply

To apply to join the hackathon, please fill out the interest form [**here**](https://docs.google.com/forms/d/e/1FAIpQLSdSi6_BCr_MNqKTPRTLSqLlQsv-OZHKlvDejfQQfKyaLPuNqw/viewform?usp=publish-editor). The application deadline is **March 13th, 2026 11:59 PM (anywhere on earth)**.

